version: '3.3'
services:
  app:
    build: ./src
    restart: always
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
  mongo:
    image: mongo:4.2.5
    expose:
      - 27017
